#This R script requires kimura.txt file generated by score.sh

md = read.table("kimura.txt",h=F,sep=";") #read file containing kimura distance for pairs of PB sequences into a data table 
md$V1=md$V1+1 #change values in first column by adding 1 to each of them
md$V2=md$V2+1 #change values in second column by adding 1 to each of them
n=max(md$V2) #calculates dimension of dissimilarity matrix
m1 = matrix (,n,n) # create a matrix to the dimension of the data
for (i in 1:n) # loop on all lines if the data table
{
	m1[md$V2[md[,1]==i],i]=md$V9[md[,1]==i] #fill dissimilarity matrix with Kimura distances
}
m1.dist=as.dist(m1)  #transform matrix into distance matrix object
m1.clust=hclust(m1.dist) #cluster the data
plot(m1.clust, main="PB-based clustering of conformations after MD", xlab="clusters", ylab="distance (Kimura)", sub="", cex=0.5, las=2) # plot clustering as dendrogram
m1.tree=cutree(m1.clust, k=7) #cut the data into 7 categories (empirically determined after examination of the tree, you can change this).
rect.hclust(m1.clust, k=7, border="red") #draw a red rectangle to delimitate the clusters: here number of clusters is 7. You can change this.


